Repository edgio-docs/edgio-docs, pull requests merged in 2022-10, with the labels that each got.

#538 Re-write search result urls to docs.edg.io
  src/components/Layout/Header/Header.tsx
Labels: do not merge

#540 Document @edgio/astro connector for Astro Apps
  src/pages/guides/astro.md
Labels: documentation

#533 use static method without cache handler in eleventy docs
  src/pages/guides/eleventy.md
Labels: question

#531 use static method without cache handler in docusaurus docs
  src/pages/guides/docusaurus.md
Labels: question

#528 remove redundant cache configs inside Next.js guide
  src/pages/guides/next.md
Labels: question

#532 use static method without cache handler in dojo docs
  src/pages/guides/dojo.md
Labels: question

#521 Create wordpress plugin guide
  layer0/plugins/ArchiveRoutes.ts
  package.json
  public/images/wordpress/deploy_token.png
  public/images/wordpress/manage_plugin.png
  public/images/wordpress/plugin_fields.png
  public/images/wordpress/plugin_settings.png
  public/images/wordpress/plugins_page.png
  public/images/wordpress/purge_activity.png
  routes.ts
  src/components/Icon/index.ts
  src/components/MDX/Integrations.tsx
  src/data/SidebarMenuItems.tsx
  src/pages/guides/wordpress.md
  yarn.lock
Labels: do not merge

#527 remove redundant SW install with Next.js guide
  src/pages/guides/next.md
Labels: question
